# Generated by Django 3.0.5 on 2020-05-19 18:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('no_control', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(100)])),
                ('sexo', models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer'), ('O', 'Otro')], max_length=1)),
                ('domicilio', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('red_social', models.CharField(blank=True, choices=[('F', 'Facebook'), ('I', 'Instagram'), ('T', 'Twitter')], max_length=30)),
                ('red_social_url', models.URLField(blank=True)),
                ('estado_actual', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descrip', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AsesoresExterno',
            fields=[
                ('no_empleado', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='AsesoresInterno',
            fields=[
                ('no_empleado', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('rfc_empresa', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('den_social', models.TextField(blank=True)),
                ('giro', models.TextField(blank=True)),
                ('responsable', models.CharField(max_length=60)),
                ('convenio', models.CharField(max_length=30)),
                ('domicio_fiscal', models.TextField()),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('url_logo', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cal_final', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('trabajo_posterior', models.CharField(choices=[('Si', 'Si'), ('No', 'No'), ('En curso', 'En curso')], max_length=8)),
                ('finalizado', models.CharField(choices=[('Si', 'Si'), ('No', 'No'), ('En curso', 'En curso')], max_length=8)),
                ('tipo_proyecto', models.CharField(choices=[('Residencias', 'Residencias'), ('Practicas', 'Practicas')], max_length=12)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registro.Alumno')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registro.Area')),
                ('asesor_externo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registro.AsesoresExterno')),
                ('asesor_interno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registro.AsesoresInterno')),
                ('empresa_rfc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registro.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal_u1', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cal_u2', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cal_u3', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cal_final', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registro.Alumno')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registro.Proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='asesoresexterno',
            name='empresa_rfc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registro.Empresa'),
        ),
    ]
