# Generated by Django 3.0.5 on 2020-06-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='solicitud_alumno',
            fields=[
                ('s_no_control', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('s_nombre', models.CharField(max_length=50)),
                ('s_carrera', models.CharField(max_length=50)),
                ('s_correo', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
