# Generated by Django 3.0.5 on 2020-06-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_solicitud_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
