# Generated by Django 3.0.5 on 2020-06-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20200601_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
