# Generated by Django 3.0.5 on 2020-06-05 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_auto_20200604_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesoresinterno',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registro.Area'),
        ),
    ]
