# Generated by Django 3.0.5 on 2020-06-05 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0010_auto_20200604_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boleta',
            old_name='cal_final',
            new_name='asesor_u1',
        ),
        migrations.RenameField(
            model_name='boleta',
            old_name='cal_u1',
            new_name='asesor_u2',
        ),
        migrations.RenameField(
            model_name='boleta',
            old_name='cal_u2',
            new_name='asesort_u3',
        ),
        migrations.RenameField(
            model_name='boleta',
            old_name='cal_u3',
            new_name='docente_u1',
        ),
        migrations.AddField(
            model_name='boleta',
            name='docente_u2',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='boleta',
            name='docente_u3',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='boleta',
            name='final',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
