# Generated by Django 3.0.5 on 2020-06-05 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0011_auto_20200605_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boleta',
            old_name='asesor_u1',
            new_name='asesor_p1',
        ),
        migrations.RenameField(
            model_name='boleta',
            old_name='asesor_u2',
            new_name='asesor_p2',
        ),
        migrations.RenameField(
            model_name='boleta',
            old_name='asesort_u3',
            new_name='asesort_p3',
        ),
        migrations.RenameField(
            model_name='boleta',
            old_name='docente_u1',
            new_name='docente_p1',
        ),
        migrations.RenameField(
            model_name='boleta',
            old_name='docente_u2',
            new_name='docente_p2',
        ),
        migrations.RenameField(
            model_name='boleta',
            old_name='docente_u3',
            new_name='docente_p3',
        ),
    ]
