# Generated by Django 3.0.5 on 2020-06-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0012_auto_20200605_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
