# Generated by Django 3.0.5 on 2020-06-09 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0013_boleta_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fecha_de_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
