# Generated by Django 3.0.5 on 2020-06-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0015_auto_20200608_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='carrera',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='semestre',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
