# Generated by Django 3.0.5 on 2020-06-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0016_auto_20200608_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='sexo',
            field=models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1),
        ),
    ]
