# Generated by Django 3.0.5 on 2020-06-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0021_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='post',
            name='titulo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
