# Generated by Django 3.0.5 on 2020-06-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0022_auto_20200610_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images_gallery/'),
        ),
    ]
