# Generated by Django 3.0.5 on 2020-06-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0023_auto_20200610_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner_gallery/')),
                ('alternative_url', models.URLField(blank=True, null=True)),
                ('redirect_url', models.URLField(blank=True, default='', null=True)),
                ('orden_aparcion', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
    ]
