# Generated by Django 3.0.5 on 2020-06-15 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0025_banner_items_redirect_page_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner_items',
            name='alternative_url',
        ),
    ]
