# Generated by Django 3.0.5 on 2020-06-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0032_auto_20200615_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesoresinterno',
            name='correo',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='asesoresinterno',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
