# Generated by Django 3.0.5 on 2020-06-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0033_auto_20200615_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='correo',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='domicilio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='estado_actual',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='red_social_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='asesoresexterno',
            name='correo',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='asesoresexterno',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='asesoresinterno',
            name='correo',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='asesoresinterno',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='banner_items',
            name='redirect_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='comentarios',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='den_social',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='giro',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
